#! /usr/bin/env python
#
# Support module generated by PAGE version 4.8.9
# In conjunction with Tcl version 8.6
#    Feb 24, 2017 07:04:51 PM
#    Feb 24, 2017 07:20:17 PM
#    Feb 27, 2017 02:26:27 AM


import sys
import webbrowser
import tkMessageBox

from os.path import expanduser

from account import *

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk

    py3 = 0
except ImportError:
    import tkinter.ttk as ttk

    py3 = 1
import defs




def auto():
    ##GET AID FROM QCMA CONFIG
    if sys.platform.__contains__("linux"):
        home = expanduser("~")
        text_file = open(home + "/.config/codestation/qcma.conf", "r")
        aid = text_file.read()
        aid = aid.splitlines()[7]
        aid = aid[14:]
        text_file.close()
        print "AID: " + aid
    if sys.platform.__contains__("win"):
        import _winreg
        qcma = _winreg.OpenKey(_winreg.HKEY_CURRENT_USER, "Software\codestation\qcma")
        aid = _winreg.QueryValueEx(qcma, "lastAccountId")
        aid = aid[0]
        print "AID: " + aid
        _winreg.closeKey()
    ##GET ACCOUNT NAME FROM QCMA CONFIG
    if sys.platform.__contains__("linux"):
        home = expanduser("~")
        text_file = open(home + "/.config/codestation/qcma.conf", "r")
        acc = text_file.read()
        acc = acc.splitlines()[8]
        acc = acc[13:]
        text_file.close()
        print "Account Name: " + acc
    if sys.platform.__contains__("win"):
        import _winreg
        qcma = _winreg.OpenKey(_winreg.HKEY_CURRENT_USER, "Software\codestation\qcma")
        acc = _winreg.QueryValueEx(qcma, "lastOnlineId")
        acc = acc[0]
        print "Account Name: " + acc
        _winreg.closeKey()

    import urllib
    print "Downloading Key From: " + "http://cma.henkaku.xyz/?aid=" + aid
    urllib.urlretrieve("http://cma.henkaku.xyz/?aid=" + aid, "tempKey.html")
    key = defs.getKey()
    print "CMA Key: " + key
    text_file = open("keys/" + acc, "w+")
    text_file.write(key)
    text_file.close()
    text_file = open("accounts/" + acc, "w+")
    text_file.write(aid)
    text_file.close()
    import account
    account.close_window(root)
    tkMessageBox.showinfo(title="Thank You!", message="Account: " + acc + " [" + aid + "] Was Registered.")
    import accMgr
    accMgr.vp_start_gui()
    sys.stdout.flush()


def addaccount(aid, acc):
    if aid == "" and acc != "" and acc.find(',') == -1:
        tkMessageBox.showinfo(title="Error 001", message="Please enter your AID.")

    if acc == "" and aid != "" and aid.find(',') == -1:
        tkMessageBox.showinfo(title="Error 002", message="Please enter Your Account Name")

    if acc == "" and aid == "":
        tkMessageBox.showinfo(title="Error 003", message="Please enter Your Account Name And your AID.")

    if len(aid) == 16:
        if acc != "" and aid != "" and acc.find(',') == -1:

            text_file = open("accounts/" +acc, "w+")
            text_file.write(aid)
            text_file.close()

            import urllib
            urllib.urlretrieve("http://cma.henkaku.xyz/?aid=" + aid, "tempKey.html")
            text_file = open("keys/"+acc,"w+")
            text_file.write(defs.getKey())
            text_file.close()

            import account
            account.close_window(root)
            tkMessageBox.showinfo(title="Thank You!", message="Account: " + acc + " [" + aid + "] Was Registered.")
            import accMgr
            accMgr.vp_start_gui()

    sys.stdout.flush()


def question():
    tkMessageBox.showinfo(title="CMA Key",message="Your AID Is The Random Numbers QCMA Puts Your Backups Inside.")
    sys.stdout.flush()


def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top


def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None


if __name__ == '__main__':
    import account

    account.vp_start_gui()



