#! /usr/bin/env python
#
# Support module generated by PAGE version 4.8.9
# In conjunction with Tcl version 8.6
#    Feb 27, 2017 07:14:29 AM
import fnmatch
import os
import sys
from symbol import import_from

import defs
import easyinstallers.ARK.main as ARK
import easyinstallers.HiddenApps.main as HiddenApps
import easyinstallers.VHBL.main as VHBL



try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

def set_Tk_var():
    # These are Tk variables used passed to Tkinter and must be
    # defined before the widgets using them are created.
    global accounts
    accounts = StringVar()


def install(plugin):
    if plugin == "ARK":
        ARK.vp_start_gui()
    elif plugin == "VHBL":
        VHBL.vp_start_gui()
    elif plugin == "HiddenApps":
        HiddenApps.run()

    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import easyInstallers
    easyInstallers.vp_start_gui()


